import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const templatePath = path.join(root, "src", "index.template.html");
const outputPath = path.join(root, "index.html");

const requiredFiles = [
  "assets/styles.css",
  "data/config.js",
  "data/countries.js",
  "data/history.js",
  "data/map-data.js",
  "js/app.js",
];

for (const relativePath of ["src/index.template.html", ...requiredFiles]) {
  if (!fs.existsSync(path.join(root, relativePath))) {
    throw new Error(`Cannot build: missing ${relativePath}`);
  }
}

const read = relativePath => fs.readFileSync(path.join(root, relativePath), "utf8").trim();
let html = fs.readFileSync(templatePath, "utf8");

html = html.replace(
  '<link rel="stylesheet" href="assets/styles.css">',
  `<style>\n${read("assets/styles.css")}\n</style>`,
);

for (const relativePath of requiredFiles.filter(file => file.endsWith(".js"))) {
  const tag = `<script src="${relativePath}"></script>`;
  if (!html.includes(tag)) throw new Error(`Template is missing ${tag}`);
  html = html.replace(tag, `<script>\n${read(relativePath)}\n</script>`);
}

const unresolved = [
  'href="assets/',
  'src="data/',
  'src="js/',
].filter(fragment => html.includes(fragment));
if (unresolved.length) throw new Error(`Build left unresolved local assets: ${unresolved.join(", ")}`);

const banner = "<!-- Generated by tools/build.mjs. Edit src/, data/, assets/ or js/ and run npm run validate. -->\n";
fs.writeFileSync(outputPath, banner + html);
console.log(`Built standalone index.html (${fs.statSync(outputPath).size} bytes).`);
