import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";
import { fetchGdelt, mapWithGentleRateLimit } from "./gdelt.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const newsPath = path.join(root, "data", "news.js");
const countriesPath = path.join(root, "data", "countries.js");

function loadBrowserGlobal(file, key) {
  const context = { window: {} };
  vm.createContext(context);
  vm.runInContext(fs.readFileSync(file, "utf8"), context, { filename: file });
  return JSON.parse(JSON.stringify(context.window[key]));
}

const countryData = loadBrowserGlobal(countriesPath, "COUNTRY_DATA");
const previous = loadBrowserGlobal(newsPath, "NEWS_DATA");
const cutoff = Date.now() - 14 * 86400000;
const failures = [];

const fetched = await mapWithGentleRateLimit(countryData.order, async key => {
  try {
    return await fetchGdelt(key, { timespan: "2d", maxrecords: 14 });
  } catch (error) {
    failures.push(error.message);
    return [];
  }
});

const countries = {};
let newArticleCount = 0;
for (const key of countryData.order) {
  const oldItems = previous.countries?.[key] || [];
  const oldUrls = new Set(oldItems.map(item => item.url));
  newArticleCount += fetched[key].filter(item => !oldUrls.has(item.url)).length;
  const byUrl = new Map([...fetched[key], ...oldItems].map(item => [item.url, item]));
  countries[key] = [...byUrl.values()]
    .filter(item => Date.parse(item.publishedAt) >= cutoff)
    .sort((a, b) => b.publishedAt.localeCompare(a.publishedAt))
    .slice(0, 14);
}

if (failures.length === countryData.order.length) {
  throw new Error(`Every news request failed; retaining the last published file. ${failures.join(" | ")}`);
}

const comparableBefore = JSON.stringify(previous.countries || {});
const comparableAfter = JSON.stringify(countries);
if (comparableBefore === comparableAfter) {
  console.log("News refresh completed with no article changes.");
  process.exit(0);
}

const output = {
  schemaVersion: 1,
  generatedAt: new Date().toISOString(),
  provider: { label: "GDELT DOC 2.0", url: "https://www.gdeltproject.org/" },
  countries
};
fs.writeFileSync(newsPath, `/* Generated by tools/update-news.mjs. Do not edit routine headlines by hand. */\nwindow.NEWS_DATA = Object.freeze(${JSON.stringify(output, null, 2)});\n`);
console.log(`News refreshed: ${newArticleCount} new article(s); ${failures.length} country request failure(s).`);
if (failures.length) failures.forEach(message => console.warn(`- ${message}`));
